### ISSUE TITLE
Must rename executable to `conda` in latest PyCharm?

### ISSUE THREAD

**Issue by jonashaag** [jonashaag/micromamba-pycharm#1]

**Comment by giamic** [comment]
Yes, I can confirm that you need to rename the python file to `conda`.

By the way, thanks for this repo, it works great!

**Comment by zhutmost** [comment]
Yes. Must rename to conda.
And another tiny bug appeared: Packages with their version numbers cannot be displayed correctly.
<img width="992" alt="image" src="https://user-images.githubusercontent.com/20497382/233426931-0494750e-0bb6-4581-959e-571eec1a2bf9.png">

Looks that the pattern matching does not work well. 
And nothing is presented in the package sub-window.
<img width="2045" alt="image" src="https://user-images.githubusercontent.com/20497382/233427346-36779dc1-a805-4a97-9edb-32bbc434d918.png">

I don't know where I can find some logs relevant to this bug. :(

**Comment by jonashaag** [comment]
I think it will be hard from the logs but maybe you can play around with the JSON output (make it "more like Conda")
