### ISSUE TITLE
Environment won't load

### ISSUE THREAD

**Issue by Pipboyguy** [jonashaag/micromamba-pycharm#3]
> Pycharm professional: 2023.2.1
> micromamba : 1.5.1

The conda environments are picked up and I'm able to select the ones available, but when I confirm my selection the interpreter stays on the old one.

![image](https://github.com/jonashaag/micromamba-pycharm/assets/34739235/6bc440a9-f9dd-47fa-b1ef-c7348c0e3699)
![image](https://github.com/jonashaag/micromamba-pycharm/assets/34739235/89e874a4-a0c5-40f4-8853-9b9d45b663ba)

**Comment by jonashaag** [comment]
Fixed. We should add tests at some point.
