### ISSUE TITLE
Syntax error line 65

### ISSUE THREAD

**Issue by ancpJR** [jonashaag/micromamba-pycharm#5]
Dear Jonas,
 great project and I tried to use it but got a syntax error here 
f'{pkg["name"]}={pkg["version"]}={pkg["build_string"]}'
any ideas?
Jochem

**Comment by jonashaag** [comment]
You need a more recent version of Python. Feel free to send a PR that makes it compatible with your older version

**Comment by jonashaag** [comment]
Now compatible with Python 2

**Comment by ancpJR** [comment]
Tanks a lot! Seems to work now ;) 

   Jochem
